title: TAPPAI
email: brand@case.edu
description: Center for Trustworthy, Agentic, Performant and Physical AI
baseurl: ""
url: "https://case-tappai.github.io"

future: false
show_drafts: false
incremental: false

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

keep_files:
  - assets
collections:
  people:
    output: true
    permalink: /team/:path/
  papers:
      output: false
      sort_by: year
    
liquid:
  error_mode: strict